# Generated by Django 4.2.5 on 2023-10-23 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={'verbose_name': 'Метка', 'verbose_name_plural': 'Метки'},
        ),
    ]
