# Generated by Django 4.2.5 on 2023-10-24 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_label_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='label',
            options={},
        ),
    ]
