# Generated by Django 4.2.5 on 2023-10-23 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0004_alter_label_options'),
        ('tasks', '0006_alter_task_label'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='label',
            field=models.ManyToManyField(blank=True, related_name='label', through='tasks.TaskLabel', to='labels.label', verbose_name='Метки'),
        ),
    ]
