# Generated by Django 4.2.5 on 2023-10-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('labels', '0005_alter_label_options'),
        ('tasks', '0007_alter_task_label'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='label',
        ),
        migrations.AddField(
            model_name='task',
            name='labels',
            field=models.ManyToManyField(blank=True, related_name='labels', through='tasks.TaskLabel', to='labels.label', verbose_name='Метки'),
        ),
    ]
